### ISSUE TITLE
Android P Wifi Analyzer Beta Works But Fails to Scan After a Few refreshes

### ISSUE THREAD

**Issue by buffal0b1ll** [VREMSoftwareDevelopment/WiFiAnalyzer#199]
I've noticed this problem on Android P dp2, dp3 and dp4 with WiFi Analyzer Beta.
Location is granted.  Have also tried enabling wifi scanning but it didn't change the behavior.

In opening the app the access points are displayed just fine.
On manual refresh, or on maybe the third or fourth scheduled refresh the Scanning progress circle comes up and then times out with network error.  Force closing the app and relaunching gets it to work again, but once more only for a few refreshes.

Thanks.

Device:  Pixel 2
Android P dp4

**Comment by buffal0b1ll** [comment]
![screenshot_20180709-084808](https://user-images.githubusercontent.com/3758447/42451311-d9a375aa-8354-11e8-83a3-1728b5f74508.png)
![screenshot_20180709-084721](https://user-images.githubusercontent.com/3758447/42451312-d9ba2f16-8354-11e8-8ffd-0ae1c21a0820.png)
![screenshot_20180709-084731](https://user-images.githubusercontent.com/3758447/42451313-d9d452b0-8354-11e8-95ee-19f9841533f5.png)

**Comment by buffal0b1ll** [comment]
Here's a log https://pastebin.com/Ws7jwrmQ

**Comment by avpavp** [comment]
I'm also running Android P Beta, I can't get any display of access points, just get the "Scanning..." screen - never shows any APs.  Running Pixel 2 XL.  Let me know if you need any testing or other info...

**Comment by buffal0b1ll** [comment]
@avpavp are you using the Wifi Analyzer Beta app?  It sounds like you might be using the stable channel WiFi Analyzer that doesn't let you grant the necessary location permission for the app to work on P.

**Comment by avpavp** [comment]
How do I get the beta?

Thanks

**Comment by avpavp** [comment]
Ok, found the beta, installed it, saw a list of APs for a couple seconds, now list is gone, and sounds like same issue as BuffaloBill.  While typing this, the APs showed up again, now they gone again, just "Scanning..."... Let me know if I can help debug...

**Comment by VREMSoftwareDevelopment** [comment]
@avpavp / @buffal0b1ll 

Can you please provide additional information, such as:
- Application version
- Application scan interval value in the settings menu

Thanks,
VREM Development Team

**Comment by buffal0b1ll** [comment]
@VREMSoftwareDevelopment sure.  Thanks for looking into this.

App Version
WiFiAnalyzer BETA (open-source) com.vrem.wifianalyzer.location 0.0.8-8S (9-28)

Scan internal value:
5s default
Also tried tapering it back to 10s to see if that helped.  Still got same result with eventual hang on scanning

**Comment by VREMSoftwareDevelopment** [comment]
This is not an application issue, it is Android P Beta issue.
Please find the following article  [WifiManager startScan throttled in Android P](https://issuetracker.google.com/issues/79906367)

**Comment by anthony-wang** [comment]
^ thanks for posting that. Hope they do implement a whitelist of sorts so that WiFi analyzer-type apps can work properly again. I use this app all the time!

**Comment by buffal0b1ll** [comment]
@VREMSoftwareDevelopment thank you.

**Comment by anthony-wang** [comment]
@VREMSoftwareDevelopment by "next BETA release", do you mean the version `v0.0.9 - 9SL (9-28)` that I just got from the Play store? I've been using it in the past 5 min or so, and haven't observed any of the throttling happening! 😃 

(Pixel XL, Android P PPP4.180612.004)

**Comment by buffal0b1ll** [comment]
I installed the new beta too.  It looks like it stops refreshing every 5
seconds after about 3 or 4 scans, but at least it doesn't leave the APs
screen and get hung on Scanning anymore.  Interestingly enough, this is how
the competitor Wifi Analyzer app on the PlayStore behaves on Android P
too.  Thanks for the fix.  It is an improvement.


--expect crazy typos--

**Comment by VREMSoftwareDevelopment** [comment]
@buffal0b1ll wrote "It looks like it stops refreshing every 5 seconds after about 3 or 4 scans"

Before application would indicate clear Android OS Wi-Fi scan failure, now it just stops refreshing access points (**False Positive**). 
Until Google fixes the "WifiManager startScan throttled in Android P" issues, the application will not work properly on Android P.

**Comment by jackfagner** [comment]
According to the Android source code the throttling will not occur if the application holds the NETWORK_SETTINGS permission.
> Note: Apps holding android.Manifest.permission.NETWORK_SETTINGS permission are exempted from scan throttling.
[WifiManager.java#739](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/wifi/java/android/net/wifi/WifiManager.java#739)

Would you mind adding this permission to the BETA?

**Comment by buffal0b1ll** [comment]
Maybe we as users could add the permission with a ADB pm command to test
this?  I'm not sure the syntax tho.


--expect crazy typos--

**Comment by jackfagner** [comment]
I just noted this:
> permission android:name="android.permission.NETWORK_SETTINGS" android:protectionLevel="signature"
[AndroidManifest.xml#1439](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/res/AndroidManifest.xml#1439)

protectionLevel="signature" means we cannot add this permission to an user app, I think :-(

**Comment by buffal0b1ll** [comment]
Thanks for that link Jack.  I think ADB might work.  I'll test.  See
https://github.com/TilesOrganization/support/wiki/How-to-use-ADB-to-grant-permissions
We use that to elevate permissions for the Tiles App which is using
  <permission android:name="android.permission.WRITE_SECURE_SETTINGS"
        android:protectionLevel="signature|privileged|development" />


--expect crazy typos--

**Comment by buffal0b1ll** [comment]
Oh well, it didn't work.  But maybe if VREM requested the permission we
could grant it thru adb.

chronos@localhost / $ adb shell pm grant
com.vrem.wifianalyzer.location android.permission.NETWORK_SETTINGS
Security exception: Package com.vrem.wifianalyzer.location has not
requested permission android.permission.NETWORK_SETTINGS

java.lang.SecurityException: Package com.vrem.wifianalyzer.location
has not requested permission android.permission.NETWORK_SETTINGS
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:379)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
        at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5411)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21260)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2796)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
        at android.os.Binder.execTransact(Binder.java:731)

**Comment by mirh** [comment]
And even if you add the thing to the manifest, you get:
```
H8314:/ $ pm grant com.vrem.wifianalyzer android.permission.NETWORK_SETTINGS
Security exception: Permission android.permission.NETWORK_SETTINGS is not a changeable permission type

java.lang.SecurityException: Permission android.permission.NETWORK_SETTINGS is not a changeable permission type
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:383)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1404)
        at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5533)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21518)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2796)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3978)
        at android.os.Binder.execTransact(Binder.java:731)
```
As pointed out [here](https://stackoverflow.com/questions/51901074/prevent-wifi-scan-throttling-on-android-9-pie-with-network-settings-permission) that's a signature level permission (which for 95% of intents and purposes means you'd need the system keys). 
Only root (or xposed?) could get you out at this point.
